### ISSUE TITLE
[Profiles Dataset] Data from 'json_data' Overflowed Out of Row

### ISSUE THREAD

**Issue by delinhquent** [junronglau/base-data-generator#1]
![profiles_dataset_issue](https://user-images.githubusercontent.com/31347372/102786871-25711980-43db-11eb-8fda-46777603c3f7.jpg)
json_data was not within the row and overflowed to other rows, causing errors when using with pandas.

**Comment by junronglau** [comment]
![image](https://user-images.githubusercontent.com/48270573/102791257-b3500300-43e1-11eb-9322-51576bd5e80c.png)

Seems to be a character limit issue in Excel, checked the number of chars in the col and it shows 32759

**Comment by delinhquent** [comment]
![image](https://user-images.githubusercontent.com/31347372/102792070-e941b700-43e2-11eb-9880-eb247bd222ef.png)

Tried to load it with Pandas and it worked! Thank you!
